extends: 'eslint:recommended'
env:
  browser: true
  es6: true
globals:
  FB: true
  gapi: true
parserOptions:
  sourceType: module
  ecmaVersion: 8
  ecmaFeatures:
    impliedStrict: true
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never