language: bash
sudo: required
dist: trusty
services:
  - docker
git:
  depth: 1
  submodules: false
branches:
  only:
  - master
env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH
before_install:
  - pip install --user awscli
install:
  - bash scripts/install.sh
before_script:
  - bash scripts/lint.sh
script:
  - bash scripts/test.sh
before_cache:
  - echo "Before Cache..."
after_success:
  - echo "After Success..."
after_failure:
  - echo "After Failure..."
before_deploy:
  - echo "Before Deploy..."
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
  skip_cleanup: true
after_deploy:
  - echo "After Deploy..."
after_script:
  - echo "After Script..."