apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: portfolio-static-site
  namespace: default
  labels:
    app: portfolio-static-site
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: portfolio-static-site
      # annotations:
    spec:
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 300
      imagePullSecrets:
      containers:
        - name: server
          image: nginx:1.13.8-alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: site
              mountPath: /static-site/
            - name: nginx
              mountPath: /etc/nginx/conf.d/default.conf
          ports:
            - name: server
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /favicon.ico
              port: 8081
              scheme: HTTP
              # httpHeaders:
              #   - name: X-Custom-Header
              #     value: Awesome
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /favicon.ico
              port: 8081
              scheme: HTTP
              # httpHeaders:
              #   - name: X-Custom-Header
              #     value: Awesome
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3
      volumes:
        - name: site
          hostPath:
            type: Directory
            path: /Users/ap5s/Development/github.com/jbacon/blog-static-site/
        - name: nginx
          hostPath:
            type: File
            path: /Users/ap5s/Development/github.com/jbacon/blog-static-site/nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio-static-site
  name: portfolio-static-site
  namespace: default
spec:
  ports:
  - name: server
    port: 8081
    nodePort: 32354
    protocol: TCP
    targetPort: 8081
  selector:
    app: portfolio-static-site
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}